name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build and test
      run: mvn clean install

    - name: Push Image
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        echo ${TOKEN} | docker login ghcr.io -u linl33 --password-stdin
        docker tag odk/sync-endpoint ghcr.io/linl33/sync-endpoint:latest
        docker push ghcr.io/linl33/sync-endpoint:latest
